      - name: Configure CMake
        run: |
          export OO_PS4_TOOLCHAIN="$HOME/OpenOrbis"

          cmake \
            -S . \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER="$HOME/OpenOrbis/llvm/bin/clang" \
            -DCMAKE_CXX_COMPILER="$HOME/OpenOrbis/llvm/bin/clang++"
